### ISSUE TITLE
sql exception - Item already added exception

### ISSUE THREAD

**Issue by msand01** [dubeaud/bugnet#134] opened 2015-06-30 22:09 UTC
I used the web deployment package located here:  http://bugnetproject.com/downloads
and installed the base version on my local Windows 8 machine with sql server 2012. Everything seems to have been installed correctly.  But when attempting to create a first project (after logging in with Admin/Password) I get :
   
Exception Details: System.ArgumentException: Item has already been added. Key in dictionary: 'Admin'  Key being added: 'Admin'

Stack Trace: 

[ArgumentException: Item has already been added. Key in dictionary: 'Admin'  Key being added: 'Admin']
   System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add) +13912903
   System.Web.Security.MembershipUserCollection.Add(MembershipUser user) +14269
   System.Web.Providers.DefaultMembershipProvider.GetAllUsers(Int32 pageIndex, Int32 pageSize, Int32& totalRecords) +375
   BugNET.Providers.MembershipProviders.ExtendedSqlMembershipProvider.GetAllUsers(Int32 pageIndex, Int32 pageSize, Int32& totalRecords) +100
   BugNET.Administration.Projects.UserControls.ProjectDescription.Initialize() +57
   BugNET.Administration.Projects.AddProject.LoadWizardStep() +346
   BugNET.Administration.Projects.AddProject.btnNext_Click(Object sender, EventArgs e) +319
   System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument) +155
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +3804
 

and am unable to add a project.  Has anyone else seen this, and can you tell me what the cause is? Thanks.

**Comment by dubeaud** [comment] 2015-07-03 12:00
Does this happen every time?

**Comment by msand01** [comment] 2015-07-04 04:54
Hi, yes, its the first time attempting to log in and I can't seem to get past it.  All the tables were created, but it keeps adding a second admin row to the users table, it will max at at 2 rows.

Date: Fri, 3 Jul 2015 05:00:30 -0700

**Comment by msand01** [comment] 2015-07-04 18:55
the answer is yes, every time :)

From: msand01@hotmail.com
To: reply@reply.github.com
Subject: RE: [bugnet] sql exception - Item already added exception (#134)
Date: Fri, 3 Jul 2015 21:54:48 -0700




Hi, yes, its the first time attempting to log in and I can't seem to get past it.  All the tables were created, but it keeps adding a second admin row to the users table, it will max at at 2 rows.

Date: Fri, 3 Jul 2015 05:00:30 -0700

**Comment by dubeaud** [comment] 2015-07-04 19:04
This looks like the same issue over here so lets continue the discussion there. https://github.com/dubeaud/bugnet/issues/125  I marked it as a bug but I don't think I got around to determining the root cause.

**Closed by dubeaud** 2015-07-04 19:04 UTC
Labels: duplicate
