### ISSUE TITLE
404 on Content/css

### ISSUE THREAD

**Issue by fgbk** [dubeaud/bugnet#149] opened 2015-09-29 09:59 UTC
Hi, i have upgrade from 1.1 to 1.6 and i am having errors with styling and login. It says "Failed to load resource: the server responded with a status of 404 (Not Found)" for the following Login.aspx:9 GET http://localhost/BugNET/Content/css?v=ZnrNzV03UMExjPzuyRXyIYj9yXT5HG_Hpa_t5cs5yzA1

**Comment by dubeaud** [comment] 2015-09-29 13:34
This is a duplicate of https://github.com/dubeaud/bugnet/issues/31

**Closed by dubeaud** 2015-09-29 13:34 UTC

**Comment by fgbk** [comment] 2015-09-29 13:52
I added the fixed from #31 and that fixed the bundles issue but i still have an issues with content/css
